nome = input('Digite seu nome completo: ').strip()
print('Analisando seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em mainúsculas é {nome.lower()}')
nospace = nome.replace(' ', '')
print(f'Seu nome tem ao todo {len(nospace)} letras')
dividido = (nome.split())
print(f'Seu primeiro nome é {dividido[0]} e ele tem {len(dividido)} letras')